language: node_js
node_js:
  - 0.10
  - 0.12
  - 4
matrix:
  allow_failures:
    - node_js: 4
sudo: false
cache:
  apt: true
  directories:
  - node_modules/
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-meanjs' ]; then cd .. && eval "mv $currentfolder generator-meanjs" && cd generator-meanjs; fi

